name: Bar workflow
on:
  pull_request:
    types: [opened, synchronized, reopened, labeled, unlabeled]

jobs:
  qux:
    runs-on: ubuntu-latest
    steps:
      - name: approve
        run: echo "A-OK"
